app:
  message: Message has been sent Successfully..
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: exchange
    queue: helloqueue
    routingkey: routing
server:
  port: 8080